name: Publish Release

on:
  push:
    tags:
      - 'v*' # Sadece v1.0, v2.3 gibi taglerde çalışır

env:
  CARGO_TERM_COLOR: always

jobs:
  release-linux:
    name: Release Linux Binary
    runs-on: ubuntu-latest
    permissions:
      contents: write # Release oluşturmak için yazma izni gerekli

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev libclang-dev cmake pkg-config build-essential

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build Release
      run: cargo build --release --verbose

    # Binary dosyasını sıkıştır (Zip)
    - name: Package Binary
      run: |
        cd target/release
        tar -czvf sentiric-cortex-linux-x64.tar.gz cortex
        mv sentiric-cortex-linux-x64.tar.gz ../../

    # GitHub Release Oluştur ve Dosyayı Yükle
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: sentiric-cortex-linux-x64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}